Sage-Bionetworks/Agora-infra

.gitignore
.travis.yml
README.md
config/config.yaml
config/develop/agoradb.yaml
templates/mongodb.yaml

* Setup a mongodb for development
* Setup travis CI to deploy infrastructure updates.

Setup mongodb on AWS

---

config/develop/agoradb.yaml
templates/mongodb.yaml

* create and use a EC2 keypair to allow toptal to access machines
* update exports with region and stack name
* update SSM parameter name for consistancy.

update infra for mongo db

---

.travis.yml
config/common/agora.yaml
templates/beanstalk-common.yaml

Setup common resources for the agora beanstalk app.

setup common resources

---

config/develop/agora.yaml
config/prod/agora.yaml
config/staging/agora.yaml

Deployments to staging and prod are failing.  Stab in the dark change
to see if this fixes the issue.

change from t2.small to t2.medium

---

config/develop/agora.yaml
config/prod/agora.yaml
config/staging/agora.yaml

Immutable deployments require enhanced health reporting.
We only enable immutable and enhanced health for prod.

Fix immutable deployment

---

.travis.yml
templates/bastian.yaml
templates/beanstalk.yaml
templates/mongodb.yaml

Setup travis to validate CF templates on PRs and fix linter errors.

[IT-446] validate templates on PRs

---

config/develop/agora.yaml
config/prod/agora.yaml
config/staging/agora.yaml
templates/beanstalk.yaml

Managed actions is the beanstalk feature that updates Node JS.

parameterize beanstalk Managed Actions

---

config/develop/agora.yaml
config/prod/agora.yaml
config/staging/agora.yaml
templates/beanstalk.yaml

Managed updates failed. Need more testing before doing it for real.

Disable managedaction

---

config/prod/agoradb.yaml

Remove replication of mongo db because the agora app is not utilizing
the replication nodes.

Remove replication

---

config/develop/agora.yaml
config/prod/agora.yaml
config/staging/agora.yaml
templates/beanstalk.yaml

* restrict valid instances to t2 and t3
* use t3 instance instead of t2

Update instances list

---

templates/bastian.yaml

Should do it.. no pre-commit on this repo?

Quarantine instance

---

templates/bastian.yaml

Reverts Sage-Bionetworks/Agora-infra#61
Should have been merged into prod

Revert "Quarantine instance"

---

templates/bastian.yaml

Reverts Sage-Bionetworks/Agora-infra#62, which is a revert of #61

Revert "Revert "Quarantine instance""

---

config/develop/agora-docdb.yaml
config/prod/agora-docdb.yaml
config/staging/agora-docdb.yaml
templates/documentdb.yaml

Setup the AWS document database service to replace
mongo db EC2 intances.

[AG-21] AWS document db service

---

templates/bastian.yaml

Switch to accessing the document db so the bastian can be used
to debug and update document databases.

[AG-21] Switch bastian host to doc db

---

config/develop/agora-docdb.yaml
config/prod/agora-docdb.yaml
config/staging/agora-docdb.yaml

Attempt to fix DB slowness by getting beefier DB instances

[AG-58] larger DB instances

---

templates/bastian.yaml

This reverts commit d0e4c29b166f97340d5ea258443f9c01882c2f15.
Revert bastian's security policy to allow accessing mongodb

[AG-60] Revert to Mongo DB

---

templates/beanstalk.yaml

Change Beanstalk load balancer to use  *.adknowledgeportal.org cert

[SC-46] switch agora certificate

---

config/misc/agora-maintenance-website.yaml

Setup a https cloudfront under maintenance website for agora.

[AG-13] maintenance website

---

config/develop/agoradb.yaml
config/prod/agoradb.yaml
config/staging/agoradb.yaml
templates/mongodb.yaml

* Update mongo db template to get fix for issue https://github.com/aws-quickstart/quickstart-mongodb/issues/46
* Removed tags from template, instead we'll set tags at the
stack level with sceptre.
* Update parameters to match existing DB deployments

Update mongo db template

---

config/develop/agoradb.yaml
config/prod/agoradb.yaml
config/staging/agoradb.yaml
templates/mongodb.yaml

The VPN setup to allow VPN access using the IpProtocol setting
didn't work.  Refactor to use the CidrIp setting.

Refactor allow VPN access

---

.travis.yml
config/develop/agora.yaml
config/prod/agora.yaml
config/prod/lambda-mongo-health-check.yaml
config/staging/agora.yaml

Should have removed references to agoradb.yaml template in
commit a25a7d5b5.  doing that in this change.

Remove referenced to agoradb

---

config/staging/agora.yaml

This change needs to be on staging branch to trigger staging rebuild.

Needs to be on staging branch

---

config/develop/agora.yaml
config/prod/agora.yaml
config/staging/agora.yaml
templates/beanstalk.yaml

This PR should increase the deployment timeout to 1000s (from default of 600s). Emma and I manually changed the timeout on staging env and the deploy succeeded.

IT-1337: Increase deploy timeout to 1000s

---

config/develop/agora.yaml
config/prod/agora.yaml
config/staging/agora.yaml

Change EC2InstanceType to `t3.large`

AG-165: Copy staging changes to prod

---

config/develop/agora.yaml
config/prod/agora.yaml
config/staging/agora.yaml

Update to node 12 based on the available version here: https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platform-history-nodejs.html

IT-1419: Update node version

---

config/develop/agora.yaml
config/prod/agora.yaml
config/staging/agora.yaml

Latest version should be v5.4.5 not v5.4.4

IT-1419: update supported version

---

.pre-commit-config.yaml
config/develop/alb-redirector.yaml
config/prod/alb-redirector.yaml
config/staging/alb-redirector.yaml
templates/alb-redirector.yaml
templates/beanstalk.yaml

This should redirect agora-staging.ampadportal.org to agora-staging.adknowledgeportal.org.

IT-1469: Merge redirect into staging

---

.pre-commit-config.yaml
.travis.yml
config/common/agora.yaml
config/develop/agora-docdb.yaml
config/develop/agora-extras.yaml
config/develop/agora.yaml
config/develop/alb-redirector.yaml
config/misc/agora-bastian.yaml
config/prod/agora-extras.yaml
config/prod/agora.yaml
config/prod/alb-redirector.yaml
config/prod/lambda-mongo-health-check.yaml
config/prod/notifications.yaml
config/staging/agora-docdb.yaml
config/staging/agora-extras.yaml
config/staging/agora.yaml
config/staging/alb-redirector.yaml

* update CI to python 3.8
* update pre-commit linters
* use sceptre template instead of template_path key

misc updates to fix build

---

config/develop/agora.yaml

...so that I can reapply it to trigger another beanstalk upgrade attempt.

Roll back platform config change
