templates/beanstalk.yaml

Use the manually generated '*.ampadportal.org' SSL certificate.
The certificate is in scicomp account however the domain is
actually hosted on sageit account.

Switch SSL certificate for HTTPS

---

templates/beanstalk.yaml

Security best practice is to capture logs for Elastic Load Balancing
with detailed information about requests sent to the Load Balancer.
Fix issue: Sage-Bionetworks/Agora#569

Enable load balancer access logs

---

.travis.yml
config/develop/agora.yaml
config/prod/agora.yaml
config/staging/agora.yaml

Immutable[1] is the only type of update that will automatically
rollback if a deployment fails. Set update to immutable for
both application and environment updates
[1] https://docs.aws.amazon.com//elasticbeanstalk/latest/dg/using-features.rolling-version-deploy.html

change deployment from rolling to immutable

---

.travis.yml
config/misc/agora-bastian.yaml

The bastian host is used for debugging and updating the database
with new data.  It is used by the agora-data-manager[1]
[1] https://github.com/Sage-Bionetworks/agora-data-manager

Setup a bastian host for agora

---

.gitignore
.travis.yml
config/common/agora.yaml
config/config.yaml
config/develop/agora.yaml
config/develop/agoradb.yaml
config/misc/agora-bastian.yaml
config/prod/agora.yaml
config/prod/agoradb.yaml
config/staging/agora.yaml
config/staging/agoradb.yaml

Upgrade from Sceptre 1.x to 2.x because V1 is end of life[1].
Followed the migration guide[2] to do the upgrade.
[1] cloudreach/sceptre#593
[2] https://github.com/cloudreach/sceptre/wiki/Migration-Guide:-V1-to-V2

[IT-435] upgrade to use Sceptre ver 2

---

templates/bastian.yaml

Fix the following cnf-lint errors:
W2030 You must specify a valid allowed value for InstanceType (hi1.4xlarge)
W2030 You must specify a valid allowed value for InstanceType (cg1.4xlarge)
those instances are not used.

Fix linter errors

---

templates/beanstalk-common.yaml
templates/beanstalk.yaml

AWS enforces a limit on the number of EB application versions that it
stores[1].  We enforce our own limit so we don't run into this error.
"You cannot have more than 500 Application Versions. Either remove some
Application Versions or request a limit increase."
[1] https://forums.aws.amazon.com/thread.jspa?threadID=159072

Set max EB deployments

---

templates/beanstalk.yaml

This will allow Beanstalk to automatically patch the Node JS platform
versions[1] for Agora.  It will also provision new instances weekly.
[1] https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/environment-platform-update-managed.html#environment-platform-update-managed-namespace

Enable auto patching of node

---

config/develop/agora.yaml
config/staging/agora.yaml

We want to enable beanstalk managed platform updates but that
feature requires enabling enhanced health reporting first.

Enable enhanced health reporting

---

.travis.yml
.yamllint

Use yamllint[1] to validate cloudformation and sceptre yaml syntax.
[1] https://github.com/adrienverge/yamllint

Syntax check yaml files

---

templates/beanstalk.yaml

Beanstalk was failing to deploy because there was not enough disk space
in the beanstalk provided instance. By default Beanstalk provisions an
8GB EBS volume. To fix we need to increase the disk space to 32GB
Failure:
```
[root@ip-10-5-51-92] cd /opt/elasticbeanstalk/hooks/appdeploy/pre
[root@ip-10-5-51-92 pre] ./20unzip.sh
..
..
inflating: /tmp/deployment/application/node_modules/typedoc/node_modules/typescript/lib/lib.esnext.intl.d.ts
inflating: /tmp/deployment/application/node_modules/typedoc/node_modules/typescript/lib/lib.d.ts
inflating: /tmp/deployment/application/node_modules/typedoc/node_modules/typescript/lib/tsc.js
/tmp/deployment/application/node_modules/typedoc/node_modules/typescript/lib/tsc.js:  write error (disk full?).  Continue? (y/n/^C) n
warning: …
```

[AG-42] fix deployment error

---

config/misc/agora-bastian.yaml
templates/bastian.yaml

The agora bastian was failing to provision due to something in
the init step, most likely the jumpcloud thing.
Instead of fixing it I've decided that we don't need jumpcloud
on this bastian.  We change it to only be accessible with the
ssh keypair

Fix agora bastian

---

templates/beanstalk.yaml

fix the following build error:
$ cfn-lint ./templates/**/*
E3012 Property Resources/R53RecordSet/Properties/TTL should be of type Long
./templates/beanstalk.yaml:177:7

fix cfn-lint error

---

config/develop/agora.yaml
config/prod/agora.yaml
config/staging/agora.yaml

This reverts commit 1ce44f8c90cd95dac6e82910a463a7ff738ea96a.
Due to performance issues with document db, https://sagebionetworks.jira.com/browse/AG-58
We've decided to rollback to mongo db, https://sagebionetworks.jira.com/browse/AG-60

Revert "[AG-21] redirect agora to doc db (#67)"

---

config/develop/agora-extras.yaml
config/prod/agora-extras.yaml
config/staging/agora-extras.yaml
templates/beanstalk-extras.yaml

Add *.ampadportal.org cert to Beanstalk ELB.
Multiple certs are not supported in beanstalk so we need to
use workaround https://github.com/awsdocs/aws-cloudformation-user-guide/issues/153#issuecomment-444714509
This depends on PR https://github.com/Sage-Bionetworks/Agora-infra/pull/59

[AG-46] Add SSL certificate

---

config/prod/lambda-mongo-health-check.yaml
config/prod/notifications.yaml
templates/notifications.yaml

Setup a lambda to monitor the Agora db.  The lambda checks the
DB every hour to verify whether it's still accessible.  Results
are sent to cloudwatch.  A notification is setup in cloudwatch
to detect connection errors.  If there are 4 consecutive connection
failures an alarm is sent to the agora-prod google group.
Users must subscribe to the agora-prod google group to receive
notifications.
Note: this is only setup to monitor the prod db instance

[AG-61] Montoring for Agora single instance DB

---

config/develop/agora.yaml
config/develop/agoradb.yaml
config/misc/agora-bastian.yaml
config/prod/agora.yaml
config/prod/agoradb.yaml
config/staging/agora.yaml
config/staging/agoradb.yaml
templates/bastian.yaml

This adds an allow policy to the instance profile that lets the SSM service connect to the agent on the instance. We need to verify that the agent is on this image or SSM will fail to connect.
Depends on https://github.com/Sage-Bionetworks/agora-data-manager/pull/17

Manage bastion

---

config/staging/agora.yaml

The failure appears to be caused by an out-of-memory error. This PR changes the type of instance to 't3.large' to get around it.

IT-1337: Change instance type for staging

---

config/develop/agora.yaml
config/prod/agora.yaml
config/staging/agora.yaml
templates/beanstalk.yaml

1. Revert deployment timeout change in this [PR](https://github.com/Sage-Bionetworks/Agora-infra/pull/99) based on code review comment in this [PR](https://github.com/Sage-Bionetworks/Agora/pull/857)
2. Change instance type to `t3.large` for dev and prod branches.

AG-165: Revert timeout and set instance type to large for all environment

---

config/develop/agora.yaml
config/prod/agora.yaml
config/staging/agora.yaml

Since agora is currently using nodejs 4.x platform version, beanstalk
only allows upating the current deployment to the latest major patch
version of the 4.x platform, which i have done.  Agora is now running
on the latest AWS supported 4.x Nodejs platform version which is
ver 4.17.9 and that includes nodejs 12.22.3 and nginx 1.18.0.
https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platform-history-nodejs.html

[IT-1448] Update to latest EB Node.js 4.x solution stack

---

templates/beanstalk.yaml

By default AWS load balancers use TLSv1.0. Our security auditor
recommends disabling the use of TLSv1.0 protocol in favor of a
cryptographically stronger TLSv1.2 protocol.
Note- TLS1.0 is compatible with a broader set of clients
(such as web browsers, mobile devices, and point-of-sale systems).
References:
https://aws.amazon.com/blogs/security/how-to-control-tls-ciphers-in-your-aws-elastic-beanstalk-application-by-using-aws-cloudformation/
https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-security-policy-table.html

[IT-1466] Use cryptographically strong TLS protocol

---

config/prod/lambda-mongo-health-check.yaml

* Pin lambda-mongo-health-check[1] dependency to a specific version to be more
stable.
* Change to using sceptre template handler instead of hooks.
[1] https://github.com/Sage-Bionetworks-IT/lambda-mongo-health-check

Pin lambda to a version
